apiVersion: batch/v1
kind: Job
metadata:
  name: eks-iam-test-ec2
spec:
  template:
    metadata:
      labels:
        app: eks-iam-test-ec2
    spec:
      serviceAccountName: iam-test
      containers:
        - name: eks-iam-test
          image: amazon/aws-cli:latest
          args: ["ec2", "describe-instances", "--region", "ap-northeast-1"]
      restartPolicy: Never
  backoffLimit: 0
